theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "focused_window"

[[block]]
block = "net"
device = "wlp3s0"
ssid = true
signal_strength = true
ip = true
speed_up = true
speed_down = true
interval = 5

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization}% {frequency}GHz"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "battery"
format = "{percentage}% {time}"
driver = "upower"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

